# 2
['prog', 'ai'],
['prog', 'ai'],
['prog', 'ai'],
['prog', 'ai'],
['prog', 'ai'],
['prog', 'ai'],
['prog', 'ai'],
['prog', 'ai'],
['prog', 'cyber'],
['prog', 'cyber'],
['prog', 'cyber'],
['prog', 'cyber'],
['prog', 'cyber'],
['prog', 'cyber'],
['prog', 'cyber'],
['prog', 'cyber'],
['prog', 'phy'],
['prog', 'phy'],
['prog', 'phy'],
['prog', 'math'],
['prog', 'math'],
['prog', 'math'],
['prog', 'math'],
['prog', 'math'],
['prog', 'math'],
['prog', 'math'],
['prog', 'math'],
['prog', 'math'],
['prog', 'math'],
['prog', 'math'],
['prog', 'math'],
['prog', 'pm'],
['prog', 'pm'],
['prog', 'pm'],
['prog', 'da'],
['prog', 'da'],
['prog', 'da'],
# end prog 2
['ai', 'prog'],
['ai', 'prog'],
['ai', 'prog'],
['ai', 'prog'],
['ai', 'prog'],
['ai', 'prog'],
['ai', 'prog'],
['ai', 'prog'],
['ai', 'cyber'],
['ai', 'cyber'],
['ai', 'cyber'],
['ai', 'cyber'],
['ai', 'phy'],
['ai', 'phy'],
['ai', 'math'],
['ai', 'math'],
['ai', 'math'],
['ai', 'math'],
['ai', 'math'],
['ai', 'pm'],
['ai', 'pm'],
['ai', 'da'],
['ai', 'da'],
# end ai 2
['cyber', 'prog'],
['cyber', 'prog'],
['cyber', 'prog'],
['cyber', 'prog'],
['cyber', 'prog'],
['cyber', 'prog'],
['cyber', 'prog'],
['cyber', 'prog'],
['cyber', 'prog'],
['cyber', 'ai'],
['cyber', 'ai'],
['cyber', 'ai'],
['cyber', 'ai'],
['cyber', 'phy'],
['cyber', 'math'],
['cyber', 'math'],
['cyber', 'math'],
['cyber', 'math'],
['cyber', 'pm'],
['cyber', 'da'],
# end cyber 2
['chem', 'math'],
['chem', 'math'],
['chem', 'math'],
['chem', 'phy'],
['chem', 'phy'],
['chem', 'phy'],
['chem', 'phy'],
['chem', 'phy'],
['chem', 'bio'],
['chem', 'bio'],
['chem', 'bio'],
['chem', 'bio'],
['chem', 'bio'],
# end chem 2
['phy', 'prog'],
['phy', 'prog'],
['phy', 'prog'],
['phy', 'ai'],
['phy', 'ai'],
['phy', 'cyber'],
['phy', 'chem'],
['phy', 'chem'],
['phy', 'chem'],
['phy', 'chem'],
['phy', 'chem'],
['phy', 'bio'],
['phy', 'bio'],
['phy', 'bio'],
['phy', 'math'],
['phy', 'math'],
['phy', 'math'],
['phy', 'math'],
['phy', 'da'],
['phy', 'da'],
# end phy 2
['bio', 'phy'],
['bio', 'phy'],
['bio', 'phy'],
['bio', 'chem'],
['bio', 'chem'],
['bio', 'chem'],
['bio', 'chem'],
['bio', 'chem'],
['bio', 'math'],
['bio', 'math'],
# end bio 2
['math', 'prog'],
['math', 'prog'],
['math', 'prog'],
['math', 'prog'],
['math', 'prog'],
['math', 'prog'],
['math', 'prog'],
['math', 'prog'],
['math', 'prog'],
['math', 'prog'],
['math', 'prog'],
['math', 'prog'],
['math', 'ai'],
['math', 'ai'],
['math', 'ai'],
['math', 'ai'],
['math', 'ai'],
['math', 'cyber'],
['math', 'cyber'],
['math', 'cyber'],
['math', 'cyber'],
['math', 'chem'],
['math', 'chem'],
['math', 'chem'],
['math', 'phy'],
['math', 'phy'],
['math', 'phy'],
['math', 'phy'],
['math', 'bio'],
['math', 'bio'],
['math', 'da'],
['math', 'da'],
['math', 'acc'],
['math', 'acc'],
['math', 'acc'],
['math', 'acc'],
['math', 'acc'],
['math', 'acc'],
['math', 'acc'],
['math', 'acc'],
['math', 'acc'],
['math', 'acc'],
# end math 2
['pm', 'prog'],
['pm', 'prog'],
['pm', 'prog'],
['pm', 'ai'],
['pm', 'ai'],
['pm', 'cyber'],
['pm', 'acc'],
['pm', 'acc'],
['pm', 'acc'],
['pm', 'acc'],
['pm', 'acc'],
['pm', 'mark'],
['pm', 'mark'],
['pm', 'mark'],
['pm', 'mark'],
['pm', 'mark'],
['pm', 'mark'],
['pm', 'fash'],
['pm', 'fash'],
['pm', 'fash'],
['pm', 'fash'],
['pm', 'music'],
['pm', 'music'],
['pm', 'music'],
['pm', 'da'],
['pm', 'da'],
# end pm 2
['acc', 'math'],
['acc', 'math'],
['acc', 'math'],
['acc', 'math'],
['acc', 'math'],
['acc', 'math'],
['acc', 'math'],
['acc', 'math'],
['acc', 'math'],
['acc', 'math'],
['acc', 'pm'],
['acc', 'pm'],
['acc', 'pm'],
['acc', 'pm'],
['acc', 'pm'],
['acc', 'mark'],
['acc', 'mark'],
# end acc 2
['mark', 'pm'],
['mark', 'pm'],
['mark', 'pm'],
['mark', 'pm'],
['mark', 'pm'],
['mark', 'pm'],
['mark', 'acc'],
['mark', 'acc'],
['mark', 'fash'],
['mark', 'fash'],
['mark', 'fash'],
['mark', 'fash'],
['mark', 'fash'],
['mark', 'music'],
['mark', 'music'],
['mark', 'music'],
['mark', 'music'],
['mark', 'music'],
['mark', 'da'],
['mark', 'da'],
['mark', 'da'],
# end mark 2
['fash', 'pm'],
['fash', 'pm'],
['fash', 'pm'],
['fash', 'pm'],
['fash', 'mark'],
['fash', 'mark'],
['fash', 'mark'],
['fash', 'mark'],
['fash', 'mark'],
['fash', 'music'],
['fash', 'music'],
['fash', 'music'],
['fash', 'da'],
['fash', 'da'],
['fash', 'da'],
['fash', 'da'],
['fash', 'da'],
['fash', 'da'],
# end fash 2
['music', 'pm'],
['music', 'pm'],
['music', 'pm'],
['music', 'mark'],
['music', 'mark'],
['music', 'mark'],
['music', 'mark'],
['music', 'mark'],
['music', 'fash'],
['music', 'fash'],
['music', 'fash'],
['music', 'da'],
['music', 'da'],
['music', 'da'],
# end music 2
['da', 'prog'],
['da', 'prog'],
['da', 'prog'],
['da', 'ai'],
['da', 'ai'],
['da', 'cyber'],
['da', 'phy'],
['da', 'phy'],
['da', 'math'],
['da', 'math'],
['da', 'pm'],
['da', 'pm'],
['da', 'mark'],
['da', 'mark'],
['da', 'mark'],
['da', 'fash'],
['da', 'fash'],
['da', 'fash'],
['da', 'fash'],
['da', 'fash'],
['da', 'fash'],
['da', 'music'],
['da', 'music'],
['da', 'music'],
# end da 2
###################################
# 3
['prog', 'ai', 'cyber'],
['prog', 'ai', 'cyber'],
['prog', 'ai', 'cyber'],
['prog', 'ai', 'cyber'],
['prog', 'ai', 'cyber'],
['prog', 'ai', 'phy'],
['prog', 'ai', 'phy'],
['prog', 'ai', 'phy'],
['prog', 'ai', 'phy'],
['prog', 'ai', 'math'],
['prog', 'ai', 'math'],
['prog', 'ai', 'math'],
['prog', 'ai', 'math'],
['prog', 'ai', 'pm'],
['prog', 'ai', 'pm'],
['prog', 'ai', 'pm'],
['prog', 'ai', 'da'],
['prog', 'ai', 'da'],
# end prog ai
['prog', 'cyber', 'ai'],
['prog', 'cyber', 'ai'],
['prog', 'cyber', 'ai'],
['prog', 'cyber', 'ai'],
['prog', 'cyber', 'ai'],
['prog', 'cyber', 'phy'],
['prog', 'cyber', 'phy'],
['prog', 'cyber', 'math'],
['prog', 'cyber', 'math'],
['prog', 'cyber', 'math'],
['prog', 'cyber', 'math'],
['prog', 'cyber', 'da'],
['prog', 'cyber', 'da'],
['prog', 'cyber', 'pm'],
['prog', 'cyber', 'pm'],
# end prog cyber
['prog', 'phy', 'ai'],
['prog', 'phy', 'ai'],
['prog', 'phy', 'cyber'],
['prog', 'phy', 'cyber'],
['prog', 'phy', 'math'],
['prog', 'phy', 'math'],
['prog', 'phy', 'math'],
['prog', 'phy', 'da'],
# end prog phy
['prog', 'math', 'ai'],
['prog', 'math', 'ai'],
['prog', 'math', 'ai'],
['prog', 'math', 'ai'],
['prog', 'math', 'cyber'],
['prog', 'math', 'cyber'],
['prog', 'math', 'cyber'],
['prog', 'math', 'cyber'],
['prog', 'math', 'phy'],
['prog', 'math', 'phy'],
['prog', 'math', 'phy'],
['prog', 'math', 'pm'],
['prog', 'math', 'pm'],
['prog', 'math', 'pm'],
['prog', 'math', 'da'],
# end prog math
['prog', 'pm', 'ai'],
['prog', 'pm', 'ai'],
['prog', 'pm', 'ai'],
['prog', 'pm', 'cyber'],
['prog', 'pm', 'cyber'],
['prog', 'pm', 'da'],
# end prog pm
['prog', 'da', 'ai'],
['prog', 'da', 'ai'],
['prog', 'da', 'cyber'],
['prog', 'da', 'cyber'],
['prog', 'da', 'phy'],
['prog', 'da', 'phy'],
['prog', 'da', 'math'],
['prog', 'da', 'math'],
['prog', 'da', 'math'],
['prog', 'da', 'pm'],
['prog', 'da', 'pm'],
# end prog da
# end prog 3
['ai', 'prog', 'cyber'],
['ai', 'prog', 'cyber'],
['ai', 'prog', 'cyber'],
['ai', 'prog', 'cyber'],
['ai', 'prog', 'cyber'],
['ai', 'prog', 'phy'],
['ai', 'prog', 'phy'],
['ai', 'prog', 'phy'],
['ai', 'prog', 'phy'],
['ai', 'prog', 'math'],
['ai', 'prog', 'math'],
['ai', 'prog', 'math'],
['ai', 'prog', 'math'],
['ai', 'prog', 'pm'],
['ai', 'prog', 'pm'],
['ai', 'prog', 'pm'],
['ai', 'prog', 'da'],
['ai', 'prog', 'da'],
# end ai prog
['ai', 'cyber', 'prog'],
['ai', 'cyber', 'prog'],
['ai', 'cyber', 'prog'],
['ai', 'cyber', 'prog'],
['ai', 'cyber', 'prog'],
['ai', 'cyber', 'phy'],
['ai', 'cyber', 'math'],
['ai', 'cyber', 'da'],
# end ai cyber
['ai', 'phy', 'prog'],
['ai', 'phy', 'cyber'],
['ai', 'phy', 'math'],
['ai', 'phy', 'da'],
# end ai phy
['ai', 'math', 'prog'],
['ai', 'math', 'cyber'],
['ai', 'math', 'phy'],
['ai', 'math', 'pm'],
['ai', 'math', 'da'],
# end ai math
['ai', 'pm', 'prog'],
['ai', 'pm', 'cyber'],
['ai', 'pm', 'phy'],
['ai', 'pm', 'da'],
# end ai pm
['ai', 'da', 'prog'],
['ai', 'da', 'cyber'],
['ai', 'da', 'phy'],
['ai', 'da', 'math'],
['ai', 'da', 'pm'],
# end ai da
['cyber', 'prog', 'ai'],
['cyber', 'prog', 'phy'],
['cyber', 'prog', 'math'],
['cyber', 'prog', 'pm'],
['cyber', 'prog', 'da'],
# end cyber prog
['cyber', 'ai', 'prog'],
['cyber', 'ai', 'phy'],
['cyber', 'ai', 'math'],
['cyber', 'ai', 'pm'],
['cyber', 'ai', 'da'],
# end cyber ai
['cyber', 'phy', 'prog'],
['cyber', 'phy', 'ai'],
['cyber', 'phy', 'math'],
['cyber', 'phy', 'pm'],
['cyber', 'phy', 'da'],
# end cyber phy
['cyber', 'math', 'prog'],
['cyber', 'math', 'ai'],
['cyber', 'math', 'phy'],
['cyber', 'math', 'pm'],
['cyber', 'math', 'da'],
# end cyber math
['cyber', 'pm', 'prog'],
['cyber', 'pm', 'ai'],
['cyber', 'pm', 'da'],
# end cyber pm
['cyber', 'da', 'prog'],
['cyber', 'da', 'ai'],
['cyber', 'da', 'phy'],
['cyber', 'da', 'math'],
['cyber', 'da', 'pm'],
# end cyber da
# end cyber 3
['chem', 'phy', 'bio'],
['chem', 'phy', 'math'],
# end chem phy
['chem', 'bio', 'phy'],
['chem', 'bio', 'math'],
# end chem bio
['chem', 'math', 'phy'],
['chem', 'math', 'bio'],
# end chem math
# end chem 3
['phy', 'prog', 'ai'],
['phy', 'prog', 'cyber'],
['phy', 'prog', 'math'],
['phy', 'prog', 'pm'],
['phy', 'prog', 'da'],
# end phy prog
['phy', 'ai', 'prog'],
['phy', 'ai', 'cyber'],
['phy', 'ai', 'math'],
['phy', 'ai', 'prog'],
['phy', 'ai', 'pm'],
['phy', 'ai', 'da'],
# end phy ai
['phy', 'cyber', 'prog'],
['phy', 'cyber', 'ai'],
['phy', 'cyber', 'matb'],
['phy', 'cyber', 'pm'],
['phy', 'cyber', 'da'],
# end phy cyber
['phy', 'chem', 'bio'],
['phy', 'chem', 'math'],
# end phy chem
['phy', 'bio', 'chem'],
['phy', 'bio', 'math'],
# end phy bio
['phy', 'math', 'prog'],
['phy', 'math', 'ai'],
['phy', 'math', 'cyber'],
['phy', 'math', 'chem'],
['phy', 'math', 'bio'],
['phy', 'math', 'da'],
# end phy math

#prog ai cyber
#chem phy bio math
#pm acc mark
#fash music da
