# Generated by Django 3.1.7 on 2021-04-01 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recSys', '0002_auto_20210401_1116'),
        ('recSys', '0002_auto_20210401_1150'),
    ]

    operations = [
    ]
