# Generated by Django 3.1.2 on 2021-04-08 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recSys', '0003_merge_20210401_1214'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
