# Generated by Django 3.1.2 on 2021-04-11 21:07

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intrest',
            name='intrests',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('cybersecurity', 'cybersecurity'), ('math', 'math'), ('project managment', 'project managment'), ('music', 'music'), ('Photography', 'Photography'), ('Fashion Design', 'Fashion Design'), ('Artificial Intelligence', 'Artificial Intelligence'), ('Accounting', 'Accounting'), ('Chemistry', 'Chemistry'), ('Marketing', 'Marketing')], max_length=124),
        ),
    ]
