# Generated by Django 3.1.2 on 2021-04-14 18:27

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210412_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intrest',
            name='intrests',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('cyber', 'Cybersecurity'), ('prog', 'Programming'), ('ai', 'Artificial Intelligence'), ('math', 'Math'), ('chem', 'Chemistry'), ('phy', 'Physics'), ('bio', 'Biology'), ('pm', 'Project Managment'), ('acc', 'Accounting'), ('mark', 'Marketing'), ('music', 'Music'), ('da', 'Digital Art'), ('fash', 'Fashion')], max_length=57),
        ),
    ]
