# Generated by Django 3.1.7 on 2021-04-14 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210414_1827'),
        ('accounts', '0003_auto_20210411_2058'),
    ]

    operations = [
    ]
