# Generated by Django 3.1.7 on 2021-04-06 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20210404_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='sub_category',
            field=models.TextField(blank=True, choices=[('Fashion', 'Fashion'), ('Music', 'Music'), ('Digital', 'Digital')], null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='sub_category',
            field=models.TextField(blank=True, choices=[('Project Managment', 'Project Managment'), ('Marketing', 'Marketing'), ('Accounting', 'Accounting')], null=True),
        ),
        migrations.AlterField(
            model_name='science',
            name='sub_category',
            field=models.TextField(blank=True, choices=[('Biology', 'Biology'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Math', 'Math')], null=True),
        ),
        migrations.AlterField(
            model_name='technology',
            name='sub_category',
            field=models.TextField(blank=True, choices=[('programming', 'programming'), ('security', 'security'), ('UX', 'UX')], null=True),
        ),
    ]
